class Const(object):
    PLUGIN_ID           = 1039115
    PLUGIN_ID_TAG       = 1039117
    VERSION             = 1.4

    #===========================================================================================================#
    #                                                                                                           #
    #                                            LIGHT TAG ID                                                   #
    #                                                                                                           #
    #===========================================================================================================#
    TAG_ID_OCTANE = 1029526
    TAG_ID_ARNOLD = 1029989
    TAG_ID_VRAY = 1020441
    LIGHT_C4D_ID = 5102
    LIGHT_ID_REDSHIFT = 1036751
    LIGHT_ID_ARNOLD = 1030424
    LIGHT_ID_CORONA = 1032104

    STEP                = 202
    RENDER_STEP         = 10000

    REDSHIFT_RENDER     = 3

    INT_MODE            = 0
    PERCENT_MODE        = 1
    METER_MODE          = 2
    FLOAT_MODE          = 3
    DEGREE_MODE         = 4

    TAG = 0
    OBJ = 1

    #===========================================================================================================#
    #                                                                                                           #
    #                                                   UI ID                                                   #
    #                                                                                                           #
    #===========================================================================================================#
    UI_BTN_OPTION = 100001
    UI_OPTION_END_OK = 100002
    UI_OPTION_END_CANCEL = 100003
    UI_OPTION_END = 100004

    UI_BTN_LICENSE = 100005
    UI_BTN_LICENSE_MAIN_GRP = 100005
    UI_BTN_LICENSE_REDSHIFT = 100007

    UI_BTN_LICENSE_REGISTER_GRP = 100010
    UI_BTN_LICENSE_INPUT = 100011
    UI_BTN_LICENSE_TYPE = 100012
    UI_BTN_LICENSE_START = 100013
    UI_BTN_LICENSE_VALID = 100014
    UI_BTN_LICENSE_CANCEL = 100015
    UI_BTN_LICENSE_OFFLINE = 100016


    GRP_MAIN = 100018
    GRP_TAB = 100019

    GRP_TAB_REDSHIFT = 100040
    GRP_TAB_REDSHIFT_SCROLL_NAME = 100041
    GRP_TAB_REDSHIFT_SCROLL_LIGHT = 100042
    GRP_TAB_REDSHIFT_SCROLL_OPT = 100043
    GRP_TAB_REDSHIFT_GRP = 100044

    GRP_OPT_TAB_REDSHIFT = 100083

    #Redshift LightLister ID
    if bool(1):
         LIGHT_LISTER_REDSHIFT_START                       = REDSHIFT_RENDER * RENDER_STEP + STEP * 1
         LIGHT_LISTER_REDSHIFT_SELECT                      = REDSHIFT_RENDER * RENDER_STEP + STEP * 2
         LIGHT_LISTER_REDSHIFT_ENABLE_VIEWPORT             = REDSHIFT_RENDER * RENDER_STEP + STEP * 3
         LIGHT_LISTER_REDSHIFT_ENABLE_RENDER               = REDSHIFT_RENDER * RENDER_STEP + STEP * 4
         LIGHT_LISTER_REDSHIFT_NAME                        = REDSHIFT_RENDER * RENDER_STEP + STEP * 5
         LIGHT_LISTER_REDSHIFT_LIGHT_TYPE                  = REDSHIFT_RENDER * RENDER_STEP + STEP * 6
         LIGHT_LISTER_REDSHIFT_PREVIEW                     = REDSHIFT_RENDER * RENDER_STEP + STEP * 7
         LIGHT_LISTER_REDSHIFT_SHOW_ILLUM                  = REDSHIFT_RENDER * RENDER_STEP + STEP * 8
         LIGHT_LISTER_REDSHIFT_AFFECT_DIFFUSE              = REDSHIFT_RENDER * RENDER_STEP + STEP * 9
         LIGHT_LISTER_REDSHIFT_AFFECT_SPECULAR             = REDSHIFT_RENDER * RENDER_STEP + STEP * 10
         LIGHT_LISTER_REDSHIFT_COLORMODE                   = REDSHIFT_RENDER * RENDER_STEP + STEP * 11
         LIGHT_LISTER_REDSHIFT_COLOR                       = REDSHIFT_RENDER * RENDER_STEP + STEP * 12
         LIGHT_LISTER_REDSHIFT_TEMP                        = REDSHIFT_RENDER * RENDER_STEP + STEP * 13
         LIGHT_LISTER_REDSHIFT_UNIT                        = REDSHIFT_RENDER * RENDER_STEP + STEP * 14
         LIGHT_LISTER_REDSHIFT_LUMEN                       = REDSHIFT_RENDER * RENDER_STEP + STEP * 15
         LIGHT_LISTER_REDSHIFT_INTENSITY                   = REDSHIFT_RENDER * RENDER_STEP + STEP * 16
         LIGHT_LISTER_REDSHIFT_DECAY_TYPE                  = REDSHIFT_RENDER * RENDER_STEP + STEP * 17
         LIGHT_LISTER_REDSHIFT_AREA_GEO                    = REDSHIFT_RENDER * RENDER_STEP + STEP * 18
         LIGHT_LISTER_REDSHIFT_AREA_SIZEX                  = REDSHIFT_RENDER * RENDER_STEP + STEP * 19
         LIGHT_LISTER_REDSHIFT_AREA_SIZEY                  = REDSHIFT_RENDER * RENDER_STEP + STEP * 20
         LIGHT_LISTER_REDSHIFT_AREA_SIZEZ                  = REDSHIFT_RENDER * RENDER_STEP + STEP * 21
         LIGHT_LISTER_REDSHIFT_AREA_VISIBLE_RENDER         = REDSHIFT_RENDER * RENDER_STEP + STEP * 22
         LIGHT_LISTER_REDSHIFT_AREA_BIDIRECTIONAL          = REDSHIFT_RENDER * RENDER_STEP + STEP * 23
         LIGHT_LISTER_REDSHIFT_AREA_NORMALIZE              = REDSHIFT_RENDER * RENDER_STEP + STEP * 24
         LIGHT_LISTER_REDSHIFT_AREA_SAMPLES                = REDSHIFT_RENDER * RENDER_STEP + STEP * 25
         LIGHT_LISTER_REDSHIFT_SPOT_ANGLE                  = REDSHIFT_RENDER * RENDER_STEP + STEP * 26
         LIGHT_LISTER_REDSHIFT_SPOT_FALLOFF                = REDSHIFT_RENDER * RENDER_STEP + STEP * 27
         LIGHT_LISTER_REDSHIFT_DOME_PATH                   = REDSHIFT_RENDER * RENDER_STEP + STEP * 28
         LIGHT_LISTER_REDSHIFT_DOME_ENVTYPE                = REDSHIFT_RENDER * RENDER_STEP + STEP * 29
         LIGHT_LISTER_REDSHIFT_DOME_APPLYEXPOSURECOMPENSATION= REDSHIFT_RENDER * RENDER_STEP + STEP * 30
         LIGHT_LISTER_REDSHIFT_DOME_GAMMA                  = REDSHIFT_RENDER * RENDER_STEP + STEP * 31
         LIGHT_LISTER_REDSHIFT_DOME_EXPOSURE               = REDSHIFT_RENDER * RENDER_STEP + STEP * 32
         LIGHT_LISTER_REDSHIFT_DOME_HUE                    = REDSHIFT_RENDER * RENDER_STEP + STEP * 33
         LIGHT_LISTER_REDSHIFT_DOME_SATURATION             = REDSHIFT_RENDER * RENDER_STEP + STEP * 34
         LIGHT_LISTER_REDSHIFT_DOME_TINT                   = REDSHIFT_RENDER * RENDER_STEP + STEP * 35
         LIGHT_LISTER_REDSHIFT_DOME_SAMPLE                 = REDSHIFT_RENDER * RENDER_STEP + STEP * 36
         LIGHT_LISTER_REDSHIFT_IES_PATH                    = REDSHIFT_RENDER * RENDER_STEP + STEP * 37
         LIGHT_LISTER_REDSHIFT_IES_COLORMODE               = REDSHIFT_RENDER * RENDER_STEP + STEP * 38
         LIGHT_LISTER_REDSHIFT_IES_COLOR                   = REDSHIFT_RENDER * RENDER_STEP + STEP * 39
         LIGHT_LISTER_REDSHIFT_IES_TEMP                    = REDSHIFT_RENDER * RENDER_STEP + STEP * 40
         LIGHT_LISTER_REDSHIFT_IES_MULT                    = REDSHIFT_RENDER * RENDER_STEP + STEP * 41
         REDSHIFT_LIGHT_PORTAL_SIZEX                       = REDSHIFT_RENDER * RENDER_STEP + STEP * 42
         REDSHIFT_LIGHT_PORTAL_SIZEY                       = REDSHIFT_RENDER * RENDER_STEP + STEP * 43
         REDSHIFT_LIGHT_PORTAL_MULTIPLIER                  = REDSHIFT_RENDER * RENDER_STEP + STEP * 44
         REDSHIFT_LIGHT_PORTAL_TINT_COLOR                  = REDSHIFT_RENDER * RENDER_STEP + STEP * 45
         REDSHIFT_LIGHT_PORTAL_TRANSPARENCY                = REDSHIFT_RENDER * RENDER_STEP + STEP * 46
         REDSHIFT_LIGHT_PORTAL_SAMPLES                     = REDSHIFT_RENDER * RENDER_STEP + STEP * 47
         REDSHIFT_LIGHT_PHYSICALSUN_MULTIPLIER             = REDSHIFT_RENDER * RENDER_STEP + STEP * 48
         REDSHIFT_LIGHT_PHYSICALSUN_USENONPHYSICALINTENSITY= REDSHIFT_RENDER * RENDER_STEP + STEP * 49
         REDSHIFT_LIGHT_PHYSICALSUN_SUN_DISK_SCALE         = REDSHIFT_RENDER * RENDER_STEP + STEP * 50
         REDSHIFT_LIGHT_PHYSICALSUN_HAZE                   = REDSHIFT_RENDER * RENDER_STEP + STEP * 51
         REDSHIFT_LIGHT_PHYSICALSUN_OZONE                  = REDSHIFT_RENDER * RENDER_STEP + STEP * 52
         REDSHIFT_LIGHT_PHYSICALSUN_HORIZON_HEIGHT         = REDSHIFT_RENDER * RENDER_STEP + STEP * 53
         REDSHIFT_LIGHT_PHYSICALSUN_REDBLUESHIFT           = REDSHIFT_RENDER * RENDER_STEP + STEP * 54
         REDSHIFT_LIGHT_PHYSICALSUN_SATURATION             = REDSHIFT_RENDER * RENDER_STEP + STEP * 55
         LIGHT_LISTER_REDSHIFT_VOLUME                      = REDSHIFT_RENDER * RENDER_STEP + STEP * 56
         LIGHT_LISTER_REDSHIFT_VOLUME_SAMPLE               = REDSHIFT_RENDER * RENDER_STEP + STEP * 57
         LIGHT_LISTER_REDSHIFT_SHADOW_ENABLE               = REDSHIFT_RENDER * RENDER_STEP + STEP * 58
         LIGHT_LISTER_REDSHIFT_SHADOW_TRANPS               = REDSHIFT_RENDER * RENDER_STEP + STEP * 59
         LIGHT_LISTER_REDSHIFT_SHADOW_SOFTNESS             = REDSHIFT_RENDER * RENDER_STEP + STEP * 60
         LIGHT_LISTER_REDSHIFT_SHADOW_SAMPLE               = REDSHIFT_RENDER * RENDER_STEP + STEP * 61
         LIGHT_LISTER_REDSHIFT_PHOTON_ENABLED              = REDSHIFT_RENDER * RENDER_STEP + STEP * 62
         LIGHT_LISTER_REDSHIFT_PHOTON_INTENSITY            = REDSHIFT_RENDER * RENDER_STEP + STEP * 63
         LIGHT_LISTER_REDSHIFT_PHOTON_NUM                  = REDSHIFT_RENDER * RENDER_STEP + STEP * 64
         LIGHT_LISTER_REDSHIFT_GI_ENABLED                  = REDSHIFT_RENDER * RENDER_STEP + STEP * 65
         LIGHT_LISTER_REDSHIFT_GI_MULITPLIER               = REDSHIFT_RENDER * RENDER_STEP + STEP * 66
         LIGHT_LISTER_REDSHIFT_GI_PHOTONS                  = REDSHIFT_RENDER * RENDER_STEP + STEP * 67
         LIGHT_LISTER_REDSHIFT_LAYERS                      = REDSHIFT_RENDER * RENDER_STEP + STEP * 68
         LIGHT_LISTER_REDSHIFT_ENABLE                      = REDSHIFT_RENDER * RENDER_STEP + STEP * 69
         LIGHT_LISTER_REDSHIFT_ORDER_GRP                   = REDSHIFT_RENDER * RENDER_STEP + STEP * 70
         LIGHT_LISTER_REDSHIFT_ORDER_UP                    = REDSHIFT_RENDER * RENDER_STEP + STEP * 71
         LIGHT_LISTER_REDSHIFT_ORDER_DOWN                  = REDSHIFT_RENDER * RENDER_STEP + STEP * 72
         LIGHT_LISTER_REDSHIFT_END                         = REDSHIFT_RENDER * RENDER_STEP + STEP * 73

    #Redshift Option LightLister ID
    if bool(1):
         LIGHT_LISTER_REDSHIFT_OPTIONS_START                       = LIGHT_LISTER_REDSHIFT_END + 1
         LIGHT_LISTER_REDSHIFT_OPTIONS_SELECT                      = LIGHT_LISTER_REDSHIFT_END + 2
         LIGHT_LISTER_REDSHIFT_OPTIONS_ENABLE_VIEWPORT             = LIGHT_LISTER_REDSHIFT_END + 3
         LIGHT_LISTER_REDSHIFT_OPTIONS_ENABLE_RENDER               = LIGHT_LISTER_REDSHIFT_END + 4
         LIGHT_LISTER_REDSHIFT_OPTIONS_NAME                        = LIGHT_LISTER_REDSHIFT_END + 5
         LIGHT_LISTER_REDSHIFT_OPTIONS_LIGHT_TYPE                  = LIGHT_LISTER_REDSHIFT_END + 6
         LIGHT_LISTER_REDSHIFT_OPTIONS_PREVIEW                     = LIGHT_LISTER_REDSHIFT_END + 7
         LIGHT_LISTER_REDSHIFT_OPTIONS_SHOW_ILLUM                  = LIGHT_LISTER_REDSHIFT_END + 8
         LIGHT_LISTER_REDSHIFT_OPTIONS_AFFECT_DIFFUSE              = LIGHT_LISTER_REDSHIFT_END + 9
         LIGHT_LISTER_REDSHIFT_OPTIONS_AFFECT_SPECULAR             = LIGHT_LISTER_REDSHIFT_END + 10
         LIGHT_LISTER_REDSHIFT_OPTIONS_COLORMODE                   = LIGHT_LISTER_REDSHIFT_END + 11
         LIGHT_LISTER_REDSHIFT_OPTIONS_COLOR                       = LIGHT_LISTER_REDSHIFT_END + 12
         LIGHT_LISTER_REDSHIFT_OPTIONS_TEMP                        = LIGHT_LISTER_REDSHIFT_END + 13
         LIGHT_LISTER_REDSHIFT_OPTIONS_UNIT                        = LIGHT_LISTER_REDSHIFT_END + 14
         LIGHT_LISTER_REDSHIFT_OPTIONS_LUMEN                       = LIGHT_LISTER_REDSHIFT_END + 15
         LIGHT_LISTER_REDSHIFT_OPTIONS_INTENSITY                   = LIGHT_LISTER_REDSHIFT_END + 16
         LIGHT_LISTER_REDSHIFT_OPTIONS_DECAY_TYPE                  = LIGHT_LISTER_REDSHIFT_END + 17
         LIGHT_LISTER_REDSHIFT_OPTIONS_AREA_GEO                    = LIGHT_LISTER_REDSHIFT_END + 18
         LIGHT_LISTER_REDSHIFT_OPTIONS_AREA_SIZEX                  = LIGHT_LISTER_REDSHIFT_END + 19
         LIGHT_LISTER_REDSHIFT_OPTIONS_AREA_SIZEY                  = LIGHT_LISTER_REDSHIFT_END + 20
         LIGHT_LISTER_REDSHIFT_OPTIONS_AREA_SIZEZ                  = LIGHT_LISTER_REDSHIFT_END + 21
         LIGHT_LISTER_REDSHIFT_OPTIONS_AREA_VISIBLE_RENDER         = LIGHT_LISTER_REDSHIFT_END + 22
         LIGHT_LISTER_REDSHIFT_OPTIONS_AREA_BIDIRECTIONAL          = LIGHT_LISTER_REDSHIFT_END + 23
         LIGHT_LISTER_REDSHIFT_OPTIONS_AREA_NORMALIZE              = LIGHT_LISTER_REDSHIFT_END + 24
         LIGHT_LISTER_REDSHIFT_OPTIONS_AREA_SAMPLES                = LIGHT_LISTER_REDSHIFT_END + 25
         LIGHT_LISTER_REDSHIFT_OPTIONS_SPOT_ANGLE                  = LIGHT_LISTER_REDSHIFT_END + 26
         LIGHT_LISTER_REDSHIFT_OPTIONS_SPOT_FALLOFF                = LIGHT_LISTER_REDSHIFT_END + 27
         LIGHT_LISTER_REDSHIFT_OPTIONS_DOME_PATH                   = LIGHT_LISTER_REDSHIFT_END + 28
         LIGHT_LISTER_REDSHIFT_OPTIONS_DOME_ENVTYPE                = LIGHT_LISTER_REDSHIFT_END + 29
         LIGHT_LISTER_REDSHIFT_OPTIONS_DOME_APPLYEXPOSURECOMPENSATION= LIGHT_LISTER_REDSHIFT_END + 30
         LIGHT_LISTER_REDSHIFT_OPTIONS_DOME_GAMMA                  = LIGHT_LISTER_REDSHIFT_END + 31
         LIGHT_LISTER_REDSHIFT_OPTIONS_DOME_EXPOSURE               = LIGHT_LISTER_REDSHIFT_END + 32
         LIGHT_LISTER_REDSHIFT_OPTIONS_DOME_HUE                    = LIGHT_LISTER_REDSHIFT_END + 33
         LIGHT_LISTER_REDSHIFT_OPTIONS_DOME_SATURATION             = LIGHT_LISTER_REDSHIFT_END + 34
         LIGHT_LISTER_REDSHIFT_OPTIONS_DOME_TINT                   = LIGHT_LISTER_REDSHIFT_END + 35
         LIGHT_LISTER_REDSHIFT_OPTIONS_DOME_SAMPLE                 = LIGHT_LISTER_REDSHIFT_END + 36
         LIGHT_LISTER_REDSHIFT_OPTIONS_IES_PATH                    = LIGHT_LISTER_REDSHIFT_END + 37
         LIGHT_LISTER_REDSHIFT_OPTIONS_IES_COLORMODE               = LIGHT_LISTER_REDSHIFT_END + 38
         LIGHT_LISTER_REDSHIFT_OPTIONS_IES_COLOR                   = LIGHT_LISTER_REDSHIFT_END + 39
         LIGHT_LISTER_REDSHIFT_OPTIONS_IES_TEMP                    = LIGHT_LISTER_REDSHIFT_END + 40
         LIGHT_LISTER_REDSHIFT_OPTIONS_IES_MULT                    = LIGHT_LISTER_REDSHIFT_END + 41
         REDSHIFT_OPTIONS_LIGHT_PORTAL_SIZEX                       = LIGHT_LISTER_REDSHIFT_END + 42
         REDSHIFT_OPTIONS_LIGHT_PORTAL_SIZEY                       = LIGHT_LISTER_REDSHIFT_END + 43
         REDSHIFT_OPTIONS_LIGHT_PORTAL_MULTIPLIER                  = LIGHT_LISTER_REDSHIFT_END + 44
         REDSHIFT_OPTIONS_LIGHT_PORTAL_TINT_COLOR                  = LIGHT_LISTER_REDSHIFT_END + 45
         REDSHIFT_OPTIONS_LIGHT_PORTAL_TRANSPARENCY                = LIGHT_LISTER_REDSHIFT_END + 46
         REDSHIFT_OPTIONS_LIGHT_PORTAL_SAMPLES                     = LIGHT_LISTER_REDSHIFT_END + 47
         REDSHIFT_OPTIONS_LIGHT_PHYSICALSUN_MULTIPLIER             = LIGHT_LISTER_REDSHIFT_END + 48
         REDSHIFT_OPTIONS_LIGHT_PHYSICALSUN_USENONPHYSICALINTENSITY= LIGHT_LISTER_REDSHIFT_END + 49
         REDSHIFT_OPTIONS_LIGHT_PHYSICALSUN_SUN_DISK_SCALE         = LIGHT_LISTER_REDSHIFT_END + 50
         REDSHIFT_OPTIONS_LIGHT_PHYSICALSUN_HAZE                   = LIGHT_LISTER_REDSHIFT_END + 51
         REDSHIFT_OPTIONS_LIGHT_PHYSICALSUN_OZONE                  = LIGHT_LISTER_REDSHIFT_END + 52
         REDSHIFT_OPTIONS_LIGHT_PHYSICALSUN_HORIZON_HEIGHT         = LIGHT_LISTER_REDSHIFT_END + 53
         REDSHIFT_OPTIONS_LIGHT_PHYSICALSUN_REDBLUESHIFT           = LIGHT_LISTER_REDSHIFT_END + 54
         REDSHIFT_OPTIONS_LIGHT_PHYSICALSUN_SATURATION             = LIGHT_LISTER_REDSHIFT_END + 55
         LIGHT_LISTER_REDSHIFT_OPTIONS_VOLUME                      = LIGHT_LISTER_REDSHIFT_END + 56
         LIGHT_LISTER_REDSHIFT_OPTIONS_VOLUME_SAMPLE               = LIGHT_LISTER_REDSHIFT_END + 57
         LIGHT_LISTER_REDSHIFT_OPTIONS_SHADOW_ENABLE               = LIGHT_LISTER_REDSHIFT_END + 58
         LIGHT_LISTER_REDSHIFT_OPTIONS_SHADOW_TRANPS               = LIGHT_LISTER_REDSHIFT_END + 59
         LIGHT_LISTER_REDSHIFT_OPTIONS_SHADOW_SOFTNESS             = LIGHT_LISTER_REDSHIFT_END + 60
         LIGHT_LISTER_REDSHIFT_OPTIONS_SHADOW_SAMPLE               = LIGHT_LISTER_REDSHIFT_END + 61
         LIGHT_LISTER_REDSHIFT_OPTIONS_PHOTON_ENABLED              = LIGHT_LISTER_REDSHIFT_END + 62
         LIGHT_LISTER_REDSHIFT_OPTIONS_PHOTON_INTENSITY            = LIGHT_LISTER_REDSHIFT_END + 63
         LIGHT_LISTER_REDSHIFT_OPTIONS_PHOTON_NUM                  = LIGHT_LISTER_REDSHIFT_END + 64
         LIGHT_LISTER_REDSHIFT_OPTIONS_GI_ENABLED                  = LIGHT_LISTER_REDSHIFT_END + 65
         LIGHT_LISTER_REDSHIFT_OPTIONS_GI_MULITPLIER               = LIGHT_LISTER_REDSHIFT_END + 66
         LIGHT_LISTER_REDSHIFT_OPTIONS_GI_PHOTONS                  = LIGHT_LISTER_REDSHIFT_END + 67
         LIGHT_LISTER_REDSHIFT_OPTIONS_LAYERS                      = LIGHT_LISTER_REDSHIFT_END + 68
         LIGHT_LISTER_REDSHIFT_OPTIONS_END                         = LIGHT_LISTER_REDSHIFT_END + 69

